// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/fixtures/protoclj/sample1.proto

package protoclj;

public final class Sample1 {
  private Sample1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValuePairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code protoclj_sample.KeyValuePair}
   */
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessage
      implements KeyValuePairOrBuilder {
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValuePair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValuePair defaultInstance;
    public static KeyValuePair getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValuePair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValuePair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclj.Sample1.internal_static_protoclj_sample_KeyValuePair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclj.Sample1.internal_static_protoclj_sample_KeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclj.Sample1.KeyValuePair.class, protoclj.Sample1.KeyValuePair.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValuePair> PARSER =
        new com.google.protobuf.AbstractParser<KeyValuePair>() {
      public KeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValuePair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValuePair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protoclj.Sample1.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protoclj.Sample1.KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protoclj.Sample1.KeyValuePair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclj_sample.KeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protoclj.Sample1.KeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclj.Sample1.internal_static_protoclj_sample_KeyValuePair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclj.Sample1.internal_static_protoclj_sample_KeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclj.Sample1.KeyValuePair.class, protoclj.Sample1.KeyValuePair.Builder.class);
      }

      // Construct using protoclj.Sample1.KeyValuePair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclj.Sample1.internal_static_protoclj_sample_KeyValuePair_descriptor;
      }

      public protoclj.Sample1.KeyValuePair getDefaultInstanceForType() {
        return protoclj.Sample1.KeyValuePair.getDefaultInstance();
      }

      public protoclj.Sample1.KeyValuePair build() {
        protoclj.Sample1.KeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoclj.Sample1.KeyValuePair buildPartial() {
        protoclj.Sample1.KeyValuePair result = new protoclj.Sample1.KeyValuePair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclj.Sample1.KeyValuePair) {
          return mergeFrom((protoclj.Sample1.KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclj.Sample1.KeyValuePair other) {
        if (other == protoclj.Sample1.KeyValuePair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclj.Sample1.KeyValuePair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclj.Sample1.KeyValuePair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoclj_sample.KeyValuePair)
    }

    static {
      defaultInstance = new KeyValuePair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoclj_sample.KeyValuePair)
  }

  public interface NestedObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required .protoclj_sample.KeyValuePair kvp = 2;
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    boolean hasKvp();
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    protoclj.Sample1.KeyValuePair getKvp();
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    protoclj.Sample1.KeyValuePairOrBuilder getKvpOrBuilder();
  }
  /**
   * Protobuf type {@code protoclj_sample.NestedObject}
   */
  public static final class NestedObject extends
      com.google.protobuf.GeneratedMessage
      implements NestedObjectOrBuilder {
    // Use NestedObject.newBuilder() to construct.
    private NestedObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NestedObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NestedObject defaultInstance;
    public static NestedObject getDefaultInstance() {
      return defaultInstance;
    }

    public NestedObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NestedObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              protoclj.Sample1.KeyValuePair.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = kvp_.toBuilder();
              }
              kvp_ = input.readMessage(protoclj.Sample1.KeyValuePair.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(kvp_);
                kvp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclj.Sample1.internal_static_protoclj_sample_NestedObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclj.Sample1.internal_static_protoclj_sample_NestedObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclj.Sample1.NestedObject.class, protoclj.Sample1.NestedObject.Builder.class);
    }

    public static com.google.protobuf.Parser<NestedObject> PARSER =
        new com.google.protobuf.AbstractParser<NestedObject>() {
      public NestedObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NestedObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NestedObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .protoclj_sample.KeyValuePair kvp = 2;
    public static final int KVP_FIELD_NUMBER = 2;
    private protoclj.Sample1.KeyValuePair kvp_;
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    public boolean hasKvp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    public protoclj.Sample1.KeyValuePair getKvp() {
      return kvp_;
    }
    /**
     * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
     */
    public protoclj.Sample1.KeyValuePairOrBuilder getKvpOrBuilder() {
      return kvp_;
    }

    private void initFields() {
      name_ = "";
      kvp_ = protoclj.Sample1.KeyValuePair.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKvp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getKvp().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, kvp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, kvp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protoclj.Sample1.NestedObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.NestedObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.NestedObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.NestedObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.NestedObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.NestedObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.NestedObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protoclj.Sample1.NestedObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.NestedObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.NestedObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protoclj.Sample1.NestedObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclj_sample.NestedObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protoclj.Sample1.NestedObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclj.Sample1.internal_static_protoclj_sample_NestedObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclj.Sample1.internal_static_protoclj_sample_NestedObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclj.Sample1.NestedObject.class, protoclj.Sample1.NestedObject.Builder.class);
      }

      // Construct using protoclj.Sample1.NestedObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKvpFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (kvpBuilder_ == null) {
          kvp_ = protoclj.Sample1.KeyValuePair.getDefaultInstance();
        } else {
          kvpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclj.Sample1.internal_static_protoclj_sample_NestedObject_descriptor;
      }

      public protoclj.Sample1.NestedObject getDefaultInstanceForType() {
        return protoclj.Sample1.NestedObject.getDefaultInstance();
      }

      public protoclj.Sample1.NestedObject build() {
        protoclj.Sample1.NestedObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoclj.Sample1.NestedObject buildPartial() {
        protoclj.Sample1.NestedObject result = new protoclj.Sample1.NestedObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (kvpBuilder_ == null) {
          result.kvp_ = kvp_;
        } else {
          result.kvp_ = kvpBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclj.Sample1.NestedObject) {
          return mergeFrom((protoclj.Sample1.NestedObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclj.Sample1.NestedObject other) {
        if (other == protoclj.Sample1.NestedObject.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasKvp()) {
          mergeKvp(other.getKvp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasKvp()) {
          
          return false;
        }
        if (!getKvp().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclj.Sample1.NestedObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclj.Sample1.NestedObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required .protoclj_sample.KeyValuePair kvp = 2;
      private protoclj.Sample1.KeyValuePair kvp_ = protoclj.Sample1.KeyValuePair.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder> kvpBuilder_;
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public boolean hasKvp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair getKvp() {
        if (kvpBuilder_ == null) {
          return kvp_;
        } else {
          return kvpBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public Builder setKvp(protoclj.Sample1.KeyValuePair value) {
        if (kvpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kvp_ = value;
          onChanged();
        } else {
          kvpBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public Builder setKvp(
          protoclj.Sample1.KeyValuePair.Builder builderForValue) {
        if (kvpBuilder_ == null) {
          kvp_ = builderForValue.build();
          onChanged();
        } else {
          kvpBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public Builder mergeKvp(protoclj.Sample1.KeyValuePair value) {
        if (kvpBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              kvp_ != protoclj.Sample1.KeyValuePair.getDefaultInstance()) {
            kvp_ =
              protoclj.Sample1.KeyValuePair.newBuilder(kvp_).mergeFrom(value).buildPartial();
          } else {
            kvp_ = value;
          }
          onChanged();
        } else {
          kvpBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public Builder clearKvp() {
        if (kvpBuilder_ == null) {
          kvp_ = protoclj.Sample1.KeyValuePair.getDefaultInstance();
          onChanged();
        } else {
          kvpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair.Builder getKvpBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getKvpFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      public protoclj.Sample1.KeyValuePairOrBuilder getKvpOrBuilder() {
        if (kvpBuilder_ != null) {
          return kvpBuilder_.getMessageOrBuilder();
        } else {
          return kvp_;
        }
      }
      /**
       * <code>required .protoclj_sample.KeyValuePair kvp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder> 
          getKvpFieldBuilder() {
        if (kvpBuilder_ == null) {
          kvpBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder>(
                  kvp_,
                  getParentForChildren(),
                  isClean());
          kvp_ = null;
        }
        return kvpBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protoclj_sample.NestedObject)
    }

    static {
      defaultInstance = new NestedObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoclj_sample.NestedObject)
  }

  public interface RepeatedObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string messages = 1;
    /**
     * <code>repeated string messages = 1;</code>
     */
    java.util.List<java.lang.String>
    getMessagesList();
    /**
     * <code>repeated string messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated string messages = 1;</code>
     */
    java.lang.String getMessages(int index);
    /**
     * <code>repeated string messages = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessagesBytes(int index);

    // repeated .protoclj_sample.KeyValuePair kvps = 2;
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    java.util.List<protoclj.Sample1.KeyValuePair> 
        getKvpsList();
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    protoclj.Sample1.KeyValuePair getKvps(int index);
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    int getKvpsCount();
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    java.util.List<? extends protoclj.Sample1.KeyValuePairOrBuilder> 
        getKvpsOrBuilderList();
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    protoclj.Sample1.KeyValuePairOrBuilder getKvpsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoclj_sample.RepeatedObject}
   */
  public static final class RepeatedObject extends
      com.google.protobuf.GeneratedMessage
      implements RepeatedObjectOrBuilder {
    // Use RepeatedObject.newBuilder() to construct.
    private RepeatedObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RepeatedObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RepeatedObject defaultInstance;
    public static RepeatedObject getDefaultInstance() {
      return defaultInstance;
    }

    public RepeatedObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RepeatedObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messages_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                kvps_ = new java.util.ArrayList<protoclj.Sample1.KeyValuePair>();
                mutable_bitField0_ |= 0x00000002;
              }
              kvps_.add(input.readMessage(protoclj.Sample1.KeyValuePair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new com.google.protobuf.UnmodifiableLazyStringList(messages_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          kvps_ = java.util.Collections.unmodifiableList(kvps_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclj.Sample1.internal_static_protoclj_sample_RepeatedObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclj.Sample1.internal_static_protoclj_sample_RepeatedObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclj.Sample1.RepeatedObject.class, protoclj.Sample1.RepeatedObject.Builder.class);
    }

    public static com.google.protobuf.Parser<RepeatedObject> PARSER =
        new com.google.protobuf.AbstractParser<RepeatedObject>() {
      public RepeatedObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RepeatedObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RepeatedObject> getParserForType() {
      return PARSER;
    }

    // repeated string messages = 1;
    public static final int MESSAGES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList messages_;
    /**
     * <code>repeated string messages = 1;</code>
     */
    public java.util.List<java.lang.String>
        getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated string messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated string messages = 1;</code>
     */
    public java.lang.String getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated string messages = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessagesBytes(int index) {
      return messages_.getByteString(index);
    }

    // repeated .protoclj_sample.KeyValuePair kvps = 2;
    public static final int KVPS_FIELD_NUMBER = 2;
    private java.util.List<protoclj.Sample1.KeyValuePair> kvps_;
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    public java.util.List<protoclj.Sample1.KeyValuePair> getKvpsList() {
      return kvps_;
    }
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    public java.util.List<? extends protoclj.Sample1.KeyValuePairOrBuilder> 
        getKvpsOrBuilderList() {
      return kvps_;
    }
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    public int getKvpsCount() {
      return kvps_.size();
    }
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    public protoclj.Sample1.KeyValuePair getKvps(int index) {
      return kvps_.get(index);
    }
    /**
     * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
     */
    public protoclj.Sample1.KeyValuePairOrBuilder getKvpsOrBuilder(
        int index) {
      return kvps_.get(index);
    }

    private void initFields() {
      messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      kvps_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getKvpsCount(); i++) {
        if (!getKvps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messages_.size(); i++) {
        output.writeBytes(1, messages_.getByteString(i));
      }
      for (int i = 0; i < kvps_.size(); i++) {
        output.writeMessage(2, kvps_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < messages_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(messages_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMessagesList().size();
      }
      for (int i = 0; i < kvps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, kvps_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protoclj.Sample1.RepeatedObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.RepeatedObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protoclj.Sample1.RepeatedObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.RepeatedObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protoclj.Sample1.RepeatedObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclj_sample.RepeatedObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protoclj.Sample1.RepeatedObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclj.Sample1.internal_static_protoclj_sample_RepeatedObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclj.Sample1.internal_static_protoclj_sample_RepeatedObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclj.Sample1.RepeatedObject.class, protoclj.Sample1.RepeatedObject.Builder.class);
      }

      // Construct using protoclj.Sample1.RepeatedObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKvpsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (kvpsBuilder_ == null) {
          kvps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          kvpsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclj.Sample1.internal_static_protoclj_sample_RepeatedObject_descriptor;
      }

      public protoclj.Sample1.RepeatedObject getDefaultInstanceForType() {
        return protoclj.Sample1.RepeatedObject.getDefaultInstance();
      }

      public protoclj.Sample1.RepeatedObject build() {
        protoclj.Sample1.RepeatedObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoclj.Sample1.RepeatedObject buildPartial() {
        protoclj.Sample1.RepeatedObject result = new protoclj.Sample1.RepeatedObject(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new com.google.protobuf.UnmodifiableLazyStringList(
              messages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
        if (kvpsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            kvps_ = java.util.Collections.unmodifiableList(kvps_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.kvps_ = kvps_;
        } else {
          result.kvps_ = kvpsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclj.Sample1.RepeatedObject) {
          return mergeFrom((protoclj.Sample1.RepeatedObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclj.Sample1.RepeatedObject other) {
        if (other == protoclj.Sample1.RepeatedObject.getDefaultInstance()) return this;
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
        if (kvpsBuilder_ == null) {
          if (!other.kvps_.isEmpty()) {
            if (kvps_.isEmpty()) {
              kvps_ = other.kvps_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureKvpsIsMutable();
              kvps_.addAll(other.kvps_);
            }
            onChanged();
          }
        } else {
          if (!other.kvps_.isEmpty()) {
            if (kvpsBuilder_.isEmpty()) {
              kvpsBuilder_.dispose();
              kvpsBuilder_ = null;
              kvps_ = other.kvps_;
              bitField0_ = (bitField0_ & ~0x00000002);
              kvpsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKvpsFieldBuilder() : null;
            } else {
              kvpsBuilder_.addAllMessages(other.kvps_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getKvpsCount(); i++) {
          if (!getKvps(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclj.Sample1.RepeatedObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclj.Sample1.RepeatedObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string messages = 1;
      private com.google.protobuf.LazyStringList messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new com.google.protobuf.LazyStringArrayList(messages_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public java.util.List<java.lang.String>
          getMessagesList() {
        return java.util.Collections.unmodifiableList(messages_);
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public int getMessagesCount() {
        return messages_.size();
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public java.lang.String getMessages(int index) {
        return messages_.get(index);
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessagesBytes(int index) {
        return messages_.getByteString(index);
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public Builder setMessages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public Builder addMessages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<java.lang.String> values) {
        ensureMessagesIsMutable();
        super.addAll(values, messages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public Builder clearMessages() {
        messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       */
      public Builder addMessagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
        return this;
      }

      // repeated .protoclj_sample.KeyValuePair kvps = 2;
      private java.util.List<protoclj.Sample1.KeyValuePair> kvps_ =
        java.util.Collections.emptyList();
      private void ensureKvpsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          kvps_ = new java.util.ArrayList<protoclj.Sample1.KeyValuePair>(kvps_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder> kvpsBuilder_;

      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public java.util.List<protoclj.Sample1.KeyValuePair> getKvpsList() {
        if (kvpsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kvps_);
        } else {
          return kvpsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public int getKvpsCount() {
        if (kvpsBuilder_ == null) {
          return kvps_.size();
        } else {
          return kvpsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair getKvps(int index) {
        if (kvpsBuilder_ == null) {
          return kvps_.get(index);
        } else {
          return kvpsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder setKvps(
          int index, protoclj.Sample1.KeyValuePair value) {
        if (kvpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvpsIsMutable();
          kvps_.set(index, value);
          onChanged();
        } else {
          kvpsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder setKvps(
          int index, protoclj.Sample1.KeyValuePair.Builder builderForValue) {
        if (kvpsBuilder_ == null) {
          ensureKvpsIsMutable();
          kvps_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvpsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder addKvps(protoclj.Sample1.KeyValuePair value) {
        if (kvpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvpsIsMutable();
          kvps_.add(value);
          onChanged();
        } else {
          kvpsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder addKvps(
          int index, protoclj.Sample1.KeyValuePair value) {
        if (kvpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvpsIsMutable();
          kvps_.add(index, value);
          onChanged();
        } else {
          kvpsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder addKvps(
          protoclj.Sample1.KeyValuePair.Builder builderForValue) {
        if (kvpsBuilder_ == null) {
          ensureKvpsIsMutable();
          kvps_.add(builderForValue.build());
          onChanged();
        } else {
          kvpsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder addKvps(
          int index, protoclj.Sample1.KeyValuePair.Builder builderForValue) {
        if (kvpsBuilder_ == null) {
          ensureKvpsIsMutable();
          kvps_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvpsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder addAllKvps(
          java.lang.Iterable<? extends protoclj.Sample1.KeyValuePair> values) {
        if (kvpsBuilder_ == null) {
          ensureKvpsIsMutable();
          super.addAll(values, kvps_);
          onChanged();
        } else {
          kvpsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder clearKvps() {
        if (kvpsBuilder_ == null) {
          kvps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          kvpsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public Builder removeKvps(int index) {
        if (kvpsBuilder_ == null) {
          ensureKvpsIsMutable();
          kvps_.remove(index);
          onChanged();
        } else {
          kvpsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair.Builder getKvpsBuilder(
          int index) {
        return getKvpsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public protoclj.Sample1.KeyValuePairOrBuilder getKvpsOrBuilder(
          int index) {
        if (kvpsBuilder_ == null) {
          return kvps_.get(index);  } else {
          return kvpsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public java.util.List<? extends protoclj.Sample1.KeyValuePairOrBuilder> 
           getKvpsOrBuilderList() {
        if (kvpsBuilder_ != null) {
          return kvpsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kvps_);
        }
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair.Builder addKvpsBuilder() {
        return getKvpsFieldBuilder().addBuilder(
            protoclj.Sample1.KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public protoclj.Sample1.KeyValuePair.Builder addKvpsBuilder(
          int index) {
        return getKvpsFieldBuilder().addBuilder(
            index, protoclj.Sample1.KeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclj_sample.KeyValuePair kvps = 2;</code>
       */
      public java.util.List<protoclj.Sample1.KeyValuePair.Builder> 
           getKvpsBuilderList() {
        return getKvpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder> 
          getKvpsFieldBuilder() {
        if (kvpsBuilder_ == null) {
          kvpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protoclj.Sample1.KeyValuePair, protoclj.Sample1.KeyValuePair.Builder, protoclj.Sample1.KeyValuePairOrBuilder>(
                  kvps_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          kvps_ = null;
        }
        return kvpsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protoclj_sample.RepeatedObject)
    }

    static {
      defaultInstance = new RepeatedObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoclj_sample.RepeatedObject)
  }

  public interface OptionalObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string text = 1;
    /**
     * <code>optional string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code protoclj_sample.OptionalObject}
   */
  public static final class OptionalObject extends
      com.google.protobuf.GeneratedMessage
      implements OptionalObjectOrBuilder {
    // Use OptionalObject.newBuilder() to construct.
    private OptionalObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OptionalObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OptionalObject defaultInstance;
    public static OptionalObject getDefaultInstance() {
      return defaultInstance;
    }

    public OptionalObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OptionalObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclj.Sample1.internal_static_protoclj_sample_OptionalObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclj.Sample1.internal_static_protoclj_sample_OptionalObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclj.Sample1.OptionalObject.class, protoclj.Sample1.OptionalObject.Builder.class);
    }

    public static com.google.protobuf.Parser<OptionalObject> PARSER =
        new com.google.protobuf.AbstractParser<OptionalObject>() {
      public OptionalObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OptionalObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protoclj.Sample1.OptionalObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.OptionalObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protoclj.Sample1.OptionalObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protoclj.Sample1.OptionalObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protoclj.Sample1.OptionalObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclj_sample.OptionalObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protoclj.Sample1.OptionalObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclj.Sample1.internal_static_protoclj_sample_OptionalObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclj.Sample1.internal_static_protoclj_sample_OptionalObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclj.Sample1.OptionalObject.class, protoclj.Sample1.OptionalObject.Builder.class);
      }

      // Construct using protoclj.Sample1.OptionalObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclj.Sample1.internal_static_protoclj_sample_OptionalObject_descriptor;
      }

      public protoclj.Sample1.OptionalObject getDefaultInstanceForType() {
        return protoclj.Sample1.OptionalObject.getDefaultInstance();
      }

      public protoclj.Sample1.OptionalObject build() {
        protoclj.Sample1.OptionalObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoclj.Sample1.OptionalObject buildPartial() {
        protoclj.Sample1.OptionalObject result = new protoclj.Sample1.OptionalObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclj.Sample1.OptionalObject) {
          return mergeFrom((protoclj.Sample1.OptionalObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclj.Sample1.OptionalObject other) {
        if (other == protoclj.Sample1.OptionalObject.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclj.Sample1.OptionalObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclj.Sample1.OptionalObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string text = 1;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoclj_sample.OptionalObject)
    }

    static {
      defaultInstance = new OptionalObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoclj_sample.OptionalObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclj_sample_KeyValuePair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoclj_sample_KeyValuePair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclj_sample_NestedObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoclj_sample_NestedObject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclj_sample_RepeatedObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoclj_sample_RepeatedObject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclj_sample_OptionalObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoclj_sample_OptionalObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$test/fixtures/protoclj/sample1.proto\022\017" +
      "protoclj_sample\"*\n\014KeyValuePair\022\013\n\003key\030\001" +
      " \002(\t\022\r\n\005value\030\002 \002(\t\"H\n\014NestedObject\022\014\n\004n" +
      "ame\030\001 \002(\t\022*\n\003kvp\030\002 \002(\0132\035.protoclj_sample" +
      ".KeyValuePair\"O\n\016RepeatedObject\022\020\n\010messa" +
      "ges\030\001 \003(\t\022+\n\004kvps\030\002 \003(\0132\035.protoclj_sampl" +
      "e.KeyValuePair\"\036\n\016OptionalObject\022\014\n\004text" +
      "\030\001 \001(\tB\n\n\010protoclj"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoclj_sample_KeyValuePair_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoclj_sample_KeyValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoclj_sample_KeyValuePair_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_protoclj_sample_NestedObject_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoclj_sample_NestedObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoclj_sample_NestedObject_descriptor,
              new java.lang.String[] { "Name", "Kvp", });
          internal_static_protoclj_sample_RepeatedObject_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protoclj_sample_RepeatedObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoclj_sample_RepeatedObject_descriptor,
              new java.lang.String[] { "Messages", "Kvps", });
          internal_static_protoclj_sample_OptionalObject_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_protoclj_sample_OptionalObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoclj_sample_OptionalObject_descriptor,
              new java.lang.String[] { "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
